name: Django Verify Code Workflow
run-name: ${{ github.actor }} run the verify workflow

on:
  workflow_call:
    inputs:
      LABELS:
        required: true
        type: string
      DOCKER_IMAGE:
        required: true
        type: string
      PYTHON_VERSION:
        required: true
        type: string
      WORKING_DIRECTORY:
        required: true
        type: string

jobs:
  django-verify:
    runs-on: ${{ fromJson(inputs.LABELS) }}
    container: ${{ inputs.DOCKER_IMAGE }}

    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Check Flake8
        run: flake8 .
      - name: Check Black
        run: black . --check
      - run: echo "🍏 This job's status is ${{ job.status }}."