on:
  workflow_call:
    inputs:
      LABELS:
        required: true
        type: string
      IMAGE_NAMES:
        required: true
        type: string
      DOCKER_COMPOSE_FILE:
        required: true
        type: string
      PROJECT_NAME:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      REGISTRY:
        required: false
        type: string
        default: ghcr.io

env: "${{secrets}}"

jobs:
  docker-deploy:
    runs-on: ${{ fromJson(inputs.LABELS) }}
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy docker
        env: ${{ fromJson( inputs.IMAGE_NAMES ) }}
        run: |
          docker-compose --project-name ${{ inputs.PROJECT_NAME }} -f ${{ inputs.DOCKER_COMPOSE_FILE }} pull
          docker-compose --project-name ${{ inputs.PROJECT_NAME }} -f ${{ inputs.DOCKER_COMPOSE_FILE }} stop
          docker-compose --project-name ${{ inputs.PROJECT_NAME }} -f ${{ inputs.DOCKER_COMPOSE_FILE }} up -d --build
